version: "3.9"
services:
  db:
    platform: linux/amd64 
    image: mysql:8.0
    container_name: mysql_db_login
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_login
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: admin
    depends_on:
      - db

volumes:
  mysql_data: